In [43]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import joblib

In [44]:
df = pd.read_csv("pima_with_hba1c.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,HbA1c
0,6,148,72,35,0,33.6,0.627,50,1,7.112748
1,1,85,66,29,0,26.6,0.351,31,0,5.048748
2,8,183,64,0,0,23.3,0.672,32,1,7.910376
3,1,89,66,23,94,28.1,0.167,21,0,5.425571
4,0,137,40,35,168,43.1,2.288,33,1,5.916640

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
 9   HbA1c                     768 non-null    float64
dtypes: float64(3), int64(7)
memory usage: 60.1 KB

In [46]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
HbA1c                       0
dtype: int64

In [47]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print(X.shape, y.shape)

(768, 9) (768,)

In [48]:
##random forest
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (614, 9)
Testing data: (154, 9)

In [49]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [50]:
y_pred = model.predict(X_test)

y_pred[:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1])

In [51]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.7467532467532467

Classification Report:

              precision    recall  f1-score   support

           0       0.80      0.81      0.80        99
           1       0.65      0.64      0.64        55

    accuracy                           0.75       154
   macro avg       0.72      0.72      0.72       154
weighted avg       0.75      0.75      0.75       154

In [52]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

import joblib

In [53]:
df = pd.read_csv("pima_with_hba1c.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,HbA1c
0,6,148,72,35,0,33.6,0.627,50,1,7.112748
1,1,85,66,29,0,26.6,0.351,31,0,5.048748
2,8,183,64,0,0,23.3,0.672,32,1,7.910376
3,1,89,66,23,94,28.1,0.167,21,0,5.425571
4,0,137,40,35,168,43.1,2.288,33,1,5.916640

In [54]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [56]:
##gradient boosting
gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [57]:
y_pred = gb_model.predict(X_test)

In [58]:
accuracy = accuracy_score(y_test, y_pred)

print("Gradient Boosting Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Gradient Boosting Accuracy: 0.7662337662337663

Classification Report:

              precision    recall  f1-score   support

           0       0.83      0.80      0.81        99
           1       0.66      0.71      0.68        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154

In [59]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

from sklearn.preprocessing import StandardScaler
import joblib

In [60]:
df = pd.read_csv("pima_with_hba1c.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,HbA1c
0,6,148,72,35,0,33.6,0.627,50,1,7.112748
1,1,85,66,29,0,26.6,0.351,31,0,5.048748
2,8,183,64,0,0,23.3,0.672,32,1,7.910376
3,1,89,66,23,94,28.1,0.167,21,0,5.425571
4,0,137,40,35,168,43.1,2.288,33,1,5.916640

In [61]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [63]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [64]:
svm_model = SVC(
    kernel='rbf',   # most powerful kernel
    C=1.0,
    gamma='scale'
)

svm_model.fit(X_train, y_train)

SVC()

In [65]:
y_pred = svm_model.predict(X_test)

In [66]:
accuracy = accuracy_score(y_test, y_pred)

print("SVM Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

SVM Accuracy: 0.7402597402597403

Classification Report:

              precision    recall  f1-score   support

           0       0.77      0.86      0.81        99
           1       0.67      0.53      0.59        55

    accuracy                           0.74       154
   macro avg       0.72      0.69      0.70       154
weighted avg       0.73      0.74      0.73       154

In [67]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
import joblib

In [68]:
df = pd.read_csv("pima_with_hba1c.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,HbA1c
0,6,148,72,35,0,33.6,0.627,50,1,7.112748
1,1,85,66,29,0,26.6,0.351,31,0,5.048748
2,8,183,64,0,0,23.3,0.672,32,1,7.910376
3,1,89,66,23,94,28.1,0.167,21,0,5.425571
4,0,137,40,35,168,43.1,2.288,33,1,5.916640

In [69]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [70]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [71]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

d:\Projects\diebeties_Risk_Predictor\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [04:22:30] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [72]:
y_pred = xgb_model.predict(X_test)

In [73]:
accuracy = accuracy_score(y_test, y_pred)

print("XGBoost Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

XGBoost Accuracy: 0.7337662337662337

Classification Report:

              precision    recall  f1-score   support

           0       0.81      0.77      0.79        99
           1       0.62      0.67      0.64        55

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.72       154
weighted avg       0.74      0.73      0.74       154

In [74]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [75]:
from sklearn.metrics import accuracy_score

accuracy1 = accuracy_score(y_test, y_pred)
print("XGBoost Accuracy:", accuracy1)

XGBoost Accuracy: 0.7337662337662337

In [76]:
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols:
    df[col] = df[col].replace(0, df[col].median())

In [77]:
## bmi is coverted to the categories of high low medium. and named as a new column bmi_category as a numeric value.
df["BMI_Category"] = pd.cut(df["BMI"],
                           bins=[0,18.5,25,30,100],
                           labels=[0,1,2,3])
df["BMI_Category"] = df["BMI_Category"].astype(int)

In [78]:
print(df["Outcome"].value_counts())

Outcome
0    500
1    268
Name: count, dtype: int64

In [79]:
from imblearn.over_sampling import SMOTE

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [81]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [82]:
from sklearn.metrics import accuracy_score

y_pred = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.83

In [83]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,HbA1c,BMI_Category
0,6,148,72,35,30.5,33.6,0.627,50,1,7.112748,3
1,1,85,66,29,30.5,26.6,0.351,31,0,5.048748,2
2,8,183,64,23,30.5,23.3,0.672,32,1,7.910376,1
3,1,89,66,23,94.0,28.1,0.167,21,0,5.425571,2
4,0,137,40,35,168.0,43.1,2.288,33,1,5.916640,3

In [84]:
import joblib
import os

os.makedirs("backend/models", exist_ok=True)

joblib.dump(xgb_model, "backend/models/model.joblib")
joblib.dump(scaler, "backend/models/scaler.joblib")

print("✅ Export done to the correct directory")

✅ Export done to the correct directory